title: LIP Computing
description: > # this means to ignore newlines until "baseurl:"
  LIP Computing documentation.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
source: ./_siteContents
